# Generated by Django 6.0.2 on 2026-02-27 11:30

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Bacon, Ovo, Maionese Extra', max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('placa_moto', models.CharField(max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('lat_atual', models.CharField(blank=True, max_length=50, null=True)),
                ('long_atual', models.CharField(blank=True, max_length=50, null=True)),
                ('pin', models.CharField(default='1234', help_text='Senha de 4 números para o App', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('ocupada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=20)),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Venda/Suprimento)'), ('SAIDA', 'Saída (Sangria/Pagamento)')], max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(default='DINHEIRO', max_length=50)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='core.caixa')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pedido', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('origem', models.CharField(choices=[('SITE', 'Site/App'), ('WHATSAPP', 'Bot WhatsApp'), ('MESA', 'Mesa (QR Code)'), ('BALCAO', 'Balcão/Caixa')], max_length=20)),
                ('motoboy_lat', models.CharField(blank=True, max_length=50, null=True)),
                ('motoboy_lng', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente_nome', models.CharField(blank=True, max_length=100)),
                ('cliente_whatsapp', models.CharField(blank=True, max_length=20)),
                ('endereco_entrega', models.TextField(blank=True)),
                ('link_rastreio', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('NOVO', 'Novo Pedido'), ('CONFIRMADO', 'Confirmado/Cozinha'), ('PRONTO', 'Pronto para Retirada/Entrega'), ('EM_TRANSITO', 'Saiu para Entrega'), ('AGUARDANDO_CAIXA', 'Aguardando Pagamento na Mesa'), ('ENTREGUE', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='NOVO', max_length=20)),
                ('forma_pagamento', models.CharField(blank=True, max_length=50)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('tipo_entrega', models.CharField(choices=[('ENTREGA', 'Delivery'), ('RETIRADA', 'Retirada na Loja'), ('MESA', 'Servir na Mesa')], default='ENTREGA', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('entregador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.entregador')),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('ativo', models.BooleanField(default=True)),
                ('tempo_preparo_estimado', models.IntegerField(default=20, help_text='Minutos')),
                ('sabores', models.CharField(blank=True, help_text='Ex: Coxinha, Bolinha de Queijo, Kibe (separe por vírgula)', max_length=500, null=True)),
                ('adicionais_disponiveis', models.ManyToManyField(blank=True, to='core.adicional')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, help_text='Ex: Sem cebola')),
                ('adicionais', models.ManyToManyField(blank=True, to='core.adicional')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Restaurante')),
                ('slug', models.SlugField(help_text='Nome na URL. Ex: salgadinho-lanches', unique=True)),
                ('aberta', models.BooleanField(default=True, verbose_name='Botão de Pânico (Forçar Abertura/Fechamento)')),
                ('horario_abertura', models.TimeField(default=datetime.time(18, 0), verbose_name='Abre às')),
                ('horario_fechamento', models.TimeField(default=datetime.time(0, 0), verbose_name='Fecha às')),
                ('mensagem_fechado', models.CharField(default='Estamos fechados no momento. Voltamos às 18h!', max_length=200, verbose_name='Aviso de Loja Fechada')),
                ('mp_access_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token Mercado Pago')),
                ('ultramsg_instance', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Instância UltraMsg')),
                ('ultramsg_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='Token UltraMsg')),
                ('lat_padrao', models.CharField(default='-22.7561', max_length=50, verbose_name='Latitude da Loja')),
                ('lng_padrao', models.CharField(default='-43.4607', max_length=50, verbose_name='Longitude da Loja')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('dono', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurante_saas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restaurante (Loja)',
                'verbose_name_plural': 'Restaurantes (Lojas)',
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurante'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurante'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurante'),
        ),
        migrations.AddField(
            model_name='entregador',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurante'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurante'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurante'),
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('taxa', models.DecimalField(decimal_places=2, default=5.0, max_digits=6, verbose_name='Taxa de Entrega (R$)')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem_rota', models.IntegerField(default=0, help_text='Ex: 1 para o seu bairro, 2 para os vizinhos, 3 para os mais distantes...', verbose_name='Ordem na Rota')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurante')),
            ],
            options={
                'ordering': ['ordem_rota', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='adicional',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurante'),
        ),
        migrations.AlterUniqueTogether(
            name='mesa',
            unique_together={('restaurante', 'numero')},
        ),
    ]
