# Generated by Django 6.0.2 on 2026-02-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='cor_principal',
            field=models.CharField(default='#FF6B00', help_text='Ex: #8B0000 para vermelho escuro', max_length=7, verbose_name='Cor Principal (HEX)'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_restaurantes/', verbose_name='Logótipo da Loja'),
        ),
    ]
