# Generated by Django 6.0.2 on 2026-02-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_restaurante_cor_principal_restaurante_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='cep',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço Físico'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='tempo_entrega',
            field=models.CharField(blank=True, default='30-45 min', max_length=50, null=True, verbose_name='Previsão de Entrega'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='cor_principal',
            field=models.CharField(default='#FF6B00', max_length=7, verbose_name='Cor Principal (HEX)'),
        ),
    ]
