# Generated by Django 6.0.2 on 2026-03-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_restaurante_cep_restaurante_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='status_assinatura',
            field=models.CharField(choices=[('TRIAL', 'Período de Teste (Grátis)'), ('ATIVO', 'Assinatura Ativa'), ('VENCIDO', 'Pagamento Atrasado (Bloqueado)')], default='TRIAL', max_length=20, verbose_name='Status do Plano'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='valor_mensalidade',
            field=models.DecimalField(decimal_places=2, default=149.9, max_digits=10, verbose_name='Valor do Plano (R$)'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='vencimento_assinatura',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento da Mensalidade'),
        ),
    ]
