# Generated by Django 6.0.2 on 2026-03-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_restaurante_status_assinatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='abre_domingo',
            field=models.BooleanField(default=True, verbose_name='Abre Domingo'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='abre_quarta',
            field=models.BooleanField(default=True, verbose_name='Abre Quarta'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='abre_quinta',
            field=models.BooleanField(default=True, verbose_name='Abre Quinta'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='abre_sabado',
            field=models.BooleanField(default=True, verbose_name='Abre Sábado'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='abre_segunda',
            field=models.BooleanField(default=True, verbose_name='Abre Segunda'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='abre_sexta',
            field=models.BooleanField(default=True, verbose_name='Abre Sexta'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='abre_terca',
            field=models.BooleanField(default=True, verbose_name='Abre Terça'),
        ),
    ]
