# Generated by Django 6.0.2 on 2026-03-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_restaurante_abre_domingo_restaurante_abre_quarta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='limite_sabores',
            field=models.IntegerField(default=2, verbose_name='Limite de Sabores / Quantidade permitida'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo_escolha_sabores',
            field=models.CharField(choices=[('CHECKBOX', 'Múltipla Escolha (Ex: Pizza Meio a Meio, Açaí)'), ('QUANTIDADE', 'Quantidade Exata (Ex: 100 Salgadinhos)')], default='CHECKBOX', max_length=15, verbose_name='Como o cliente escolhe os Sabores?'),
        ),
    ]
