# Generated by Django 6.0.2 on 2026-03-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_produto_limite_sabores_produto_tipo_escolha_sabores'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_diario',
            field=models.IntegerField(blank=True, null=True, verbose_name='Senha do Dia'),
        ),
    ]
